namespace NkChinh.DI.Generator;

internal static class GeneratorInfo
{
    public const string Name = "NkChinh.DI.Generator";
    public const string Version = "0.0.0";
}

/// <summary>
/// Source embedded into every consuming project so the package needs no runtime assembly.
/// All types are internal; consumers can opt out (e.g. for InternalsVisibleTo conflicts)
/// by defining DIGEN_EXCLUDE_ATTRIBUTES and supplying the types themselves.
/// </summary>
internal static class EmbeddedSources
{
    public const string AttributesHintName = "DIGenAttributes.g.cs";

    public static readonly string Attributes = $$"""
        // <auto-generated by {{GeneratorInfo.Name}} />
        #if !DIGEN_EXCLUDE_ATTRIBUTES
        #nullable enable
        #pragma warning disable

        namespace DIGen
        {
            /// <summary>Registers the class as a singleton service using its concrete type.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class SingletonServiceAttribute : global::System.Attribute
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public SingletonServiceAttribute() { }

                public SingletonServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a singleton service exposed as <typeparamref name="TService"/>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class SingletonServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public SingletonServiceAttribute() { }

                public SingletonServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a scoped service using its concrete type.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ScopedServiceAttribute : global::System.Attribute
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public ScopedServiceAttribute() { }

                public ScopedServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a scoped service exposed as <typeparamref name="TService"/>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ScopedServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public ScopedServiceAttribute() { }

                public ScopedServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a transient service using its concrete type.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class TransientServiceAttribute : global::System.Attribute
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public TransientServiceAttribute() { }

                public TransientServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a transient service exposed as <typeparamref name="TService"/>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class TransientServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public TransientServiceAttribute() { }

                public TransientServiceAttribute(string key) { Key = key; }
            }

            /// <summary>
            /// Marks an instance field or property for constructor injection. All [Inject] members of a
            /// partial class are grouped into a single generated constructor. When the member carries a
            /// key (e.g. <c>[Inject("email")]</c>), the key is honored by the factory delegate a
            /// referencing host project generates against Microsoft.Extensions.DependencyInjection.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            internal sealed class InjectAttribute : global::System.Attribute
            {
                /// <summary>Optional service key for keyed dependency injection.</summary>
                public string? Key { get; }

                public InjectAttribute() { }

                public InjectAttribute(string key) { Key = key; }
            }

            /// <summary>Lifetime values used by scope-locking attributes; independent of any DI package.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            internal enum DiServiceScope
            {
                Singleton = 0,
                Scoped = 1,
                Transient = 2,
            }

            /// <summary>
            /// Locks the lifetime any registration of this interface must use. Combine with
            /// <see cref="ServiceAttribute{TService}"/> to have the lifetime resolved automatically, or with
            /// an explicit lifetime attribute to have it checked for you.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
            internal sealed class RequiredScopeAttribute : global::System.Attribute
            {
                public RequiredScopeAttribute(DiServiceScope lifetime)
                {
                    Lifetime = lifetime;
                }

                public DiServiceScope Lifetime { get; }
            }

            /// <summary>
            /// Locks the lifetime a type this project doesn't own (a third-party interface, a <c>DbContext</c>, …)
            /// must use. Apply at assembly level in any project that directly references the type, so the
            /// type's own project never needs a dependency on it.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class RequiredExternalScopeAttribute : global::System.Attribute
            {
                public RequiredExternalScopeAttribute(global::System.Type interfaceType, DiServiceScope lifetime)
                {
                    InterfaceType = interfaceType;
                    Lifetime = lifetime;
                }

                public global::System.Type InterfaceType { get; }

                public DiServiceScope Lifetime { get; }
            }

            /// <summary>
            /// Registers the class as <typeparamref name="TService"/> using whatever lifetime
            /// <typeparamref name="TService"/> is locked to via <see cref="RequiredScopeAttribute"/> or
            /// <see cref="RequiredExternalScopeAttribute"/>.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public ServiceAttribute() { }

                public ServiceAttribute(string key) { Key = key; }
            }

            /// <summary>
            /// Resolves [Inject] constructor parameters from an <see cref="global::System.IServiceProvider"/>
            /// using only BCL types — no dependency on Microsoft.Extensions.DependencyInjection.
            /// Generated constructors reference this helper via factory delegates when a class has
            /// both a generated [Inject] constructor and user-defined constructors.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            internal static class InjectServiceResolver
            {
                /// <summary>Resolves a required service; throws when missing.</summary>
                public static T GetRequired<T>(global::System.IServiceProvider sp)
                {
                    var service = sp.GetService(typeof(T));
                    if (service is null)
                        throw new global::System.InvalidOperationException(
                            $"Cannot resolve service '{typeof(T)}' for constructor injection.");
                    return (T)service;
                }

                /// <summary>Resolves an optional service, returning null when missing.</summary>
                public static T? GetOptional<T>(global::System.IServiceProvider sp) where T : class
                {
                    return (T?)sp.GetService(typeof(T));
                }
            }
        }

        namespace DIGen.Generated
        {
            /// <summary>
            /// Assembly-level definition of one registered service and its [Inject] members, published
            /// by the owning assembly at compile time. A project that references this assembly and can
            /// resolve Microsoft.Extensions.DependencyInjection reads these definitions and generates
            /// direct <c>Add{...}Services</c> registrations from them — no re-derivation, no scan of
            /// class metadata. Infrastructure attribute — do not apply manually.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class ServiceDefinitionAttribute : global::System.Attribute
            {
                public ServiceDefinitionAttribute(
                    global::System.Type implementationType,
                    global::System.Type serviceType,
                    int lifetime,
                    string? key,
                    bool isHostedService,
                    bool requiresFactory,
                    string[] memberNames,
                    global::System.Type[] memberTypes,
                    string[] memberKeys,
                    bool[] memberOptionals)
                {
                    ImplementationType = implementationType;
                    ServiceType = serviceType;
                    Lifetime = lifetime;
                    Key = key;
                    IsHostedService = isHostedService;
                    RequiresFactory = requiresFactory;
                    MemberNames = memberNames;
                    MemberTypes = memberTypes;
                    MemberKeys = memberKeys;
                    MemberOptionals = memberOptionals;
                }

                /// <summary>The class implementing the service.</summary>
                public global::System.Type ImplementationType { get; }

                /// <summary>The registered service type; equals <see cref="ImplementationType"/> for self-registration.</summary>
                public global::System.Type ServiceType { get; }

                /// <summary><c>DiServiceScope</c> value already resolved against scope-locking rules by the owner.</summary>
                public int Lifetime { get; }

                /// <summary>Service key, or null when not registered as keyed.</summary>
                public string? Key { get; }

                /// <summary>Whether the implementation should be registered as an <c>IHostedService</c>.</summary>
                public bool IsHostedService { get; }

                /// <summary>Whether registration requires a generated factory for constructor selection, keyed injection, or optional injection.</summary>
                public bool RequiresFactory { get; }

                /// <summary>Names of the [Inject] members, in generated-constructor order.</summary>
                public string[] MemberNames { get; }

                /// <summary>Types of the [Inject] members, index-aligned with <see cref="MemberNames"/>.</summary>
                public global::System.Type[] MemberTypes { get; }

                /// <summary>Key of each [Inject] member ("" = none), index-aligned with <see cref="MemberNames"/>.</summary>
                public string[] MemberKeys { get; }

                /// <summary>Optionality of each [Inject] member, index-aligned with <see cref="MemberNames"/>.</summary>
                public bool[] MemberOptionals { get; }
            }
        }
        #endif
        """;

    public const string LifetimeExtensionsHintName = "DiServiceScopeExtensions.g.cs";

    /// <summary>
    /// Embedded only when the compilation can resolve Microsoft.Extensions.DependencyInjection.ServiceLifetime,
    /// so the always-embedded DiServiceScope enum keeps working in projects with no MEDI dependency.
    /// </summary>
    public static readonly string LifetimeExtensions = $$"""
        // <auto-generated by {{GeneratorInfo.Name}} />
        #if !DIGEN_EXCLUDE_ATTRIBUTES
        #nullable enable
        #pragma warning disable

        namespace DIGen
        {
            /// <summary>Maps <see cref="DiServiceScope"/> to Microsoft.Extensions.DependencyInjection.ServiceLifetime.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            internal static class DiServiceScopeExtensions
            {
                public static global::Microsoft.Extensions.DependencyInjection.ServiceLifetime ToServiceLifetime(
                    this DiServiceScope lifetime) => lifetime switch
                {
                    DiServiceScope.Singleton => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton,
                    DiServiceScope.Scoped => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped,
                    DiServiceScope.Transient => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient,
                    _ => throw new global::System.ArgumentOutOfRangeException(nameof(lifetime)),
                };
            }
        }
        #endif
        """;
}
