namespace NkChinh.DI.Generator;

internal static class GeneratorInfo
{
    public const string Name = "NkChinh.DI.Generator";
    public const string Version = "0.0.0";
}

/// <summary>
/// Source embedded into every consuming project so the package needs no runtime assembly.
/// All types are internal; consumers can opt out (e.g. for InternalsVisibleTo conflicts)
/// by defining DIGEN_EXCLUDE_ATTRIBUTES and supplying the types themselves.
/// </summary>
internal static class EmbeddedSources
{
    public const string AttributesHintName = "DIGenAttributes.g.cs";

    public static readonly string Attributes = $$"""
        // <auto-generated by {{GeneratorInfo.Name}} />
        #if !DIGEN_EXCLUDE_ATTRIBUTES
        #nullable enable
        #pragma warning disable

        namespace DIGen
        {
            /// <summary>Registers the class as a singleton service using its concrete type.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class SingletonServiceAttribute : global::System.Attribute
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public SingletonServiceAttribute() { }

                public SingletonServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a singleton service exposed as <typeparamref name="TService"/>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class SingletonServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public SingletonServiceAttribute() { }

                public SingletonServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a scoped service using its concrete type.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ScopedServiceAttribute : global::System.Attribute
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public ScopedServiceAttribute() { }

                public ScopedServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a scoped service exposed as <typeparamref name="TService"/>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ScopedServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public ScopedServiceAttribute() { }

                public ScopedServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a transient service using its concrete type.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class TransientServiceAttribute : global::System.Attribute
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public TransientServiceAttribute() { }

                public TransientServiceAttribute(string key) { Key = key; }
            }

            /// <summary>Registers the class as a transient service exposed as <typeparamref name="TService"/>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class TransientServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public TransientServiceAttribute() { }

                public TransientServiceAttribute(string key) { Key = key; }
            }

            /// <summary>
            /// Marks an instance field or property for constructor injection. All [Inject] members of a
            /// partial class are grouped into a single generated constructor.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            internal sealed class InjectAttribute : global::System.Attribute
            {
            }

            /// <summary>Lifetime values used by scope-locking attributes; independent of any DI package.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            internal enum DiServiceScope
            {
                Singleton = 0,
                Scoped = 1,
                Transient = 2,
            }

            /// <summary>
            /// Locks the lifetime any registration of this interface must use. Combine with
            /// <see cref="ServiceAttribute{TService}"/> to have the lifetime resolved automatically, or with
            /// an explicit lifetime attribute to have it checked for you.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
            internal sealed class RequiredScopeAttribute : global::System.Attribute
            {
                public RequiredScopeAttribute(DiServiceScope lifetime)
                {
                    Lifetime = lifetime;
                }

                public DiServiceScope Lifetime { get; }
            }

            /// <summary>
            /// Locks the lifetime a type this project doesn't own (a third-party interface, a <c>DbContext</c>, …)
            /// must use. Apply at assembly level in any project that directly references the type, so the
            /// type's own project never needs a dependency on it.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class RequiredExternalScopeAttribute : global::System.Attribute
            {
                public RequiredExternalScopeAttribute(global::System.Type interfaceType, DiServiceScope lifetime)
                {
                    InterfaceType = interfaceType;
                    Lifetime = lifetime;
                }

                public global::System.Type InterfaceType { get; }

                public DiServiceScope Lifetime { get; }
            }

            /// <summary>
            /// Registers the class as <typeparamref name="TService"/> using whatever lifetime
            /// <typeparamref name="TService"/> is locked to via <see cref="RequiredScopeAttribute"/> or
            /// <see cref="RequiredExternalScopeAttribute"/>.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ServiceAttribute<TService> : global::System.Attribute
                where TService : class
            {
                /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
                public string? Key { get; }

                public ServiceAttribute() { }

                public ServiceAttribute(string key) { Key = key; }
            }
        }

        namespace DIGen.Generated
        {
            /// <summary>
            /// Assembly-level marker describing this assembly's generated registration module.
            /// Referencing projects use it to generate an aggregator that chains all modules.
            /// Infrastructure attribute — do not apply manually.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class ServiceRegistrationModuleAttribute : global::System.Attribute
            {
                public ServiceRegistrationModuleAttribute(string methodName, string extensionsTypeName)
                {
                    MethodName = methodName;
                    ExtensionsTypeName = extensionsTypeName;
                }

                /// <summary>Name of the generated extension method, e.g. AddMyCompanyInfrastructureServices.</summary>
                public string MethodName { get; }

                /// <summary>Fully qualified name (without global::) of the static class declaring the method.</summary>
                public string ExtensionsTypeName { get; }
            }
        }
        #endif
        """;

    public const string LifetimeExtensionsHintName = "DiServiceScopeExtensions.g.cs";

    /// <summary>
    /// Embedded only when the compilation can resolve Microsoft.Extensions.DependencyInjection.ServiceLifetime,
    /// so the always-embedded DiServiceScope enum keeps working in projects with no MEDI dependency.
    /// </summary>
    public static readonly string LifetimeExtensions = $$"""
        // <auto-generated by {{GeneratorInfo.Name}} />
        #if !DIGEN_EXCLUDE_ATTRIBUTES
        #nullable enable
        #pragma warning disable

        namespace DIGen
        {
            /// <summary>Maps <see cref="DiServiceScope"/> to Microsoft.Extensions.DependencyInjection.ServiceLifetime.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            internal static class DiServiceScopeExtensions
            {
                public static global::Microsoft.Extensions.DependencyInjection.ServiceLifetime ToServiceLifetime(
                    this DiServiceScope lifetime) => lifetime switch
                {
                    DiServiceScope.Singleton => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton,
                    DiServiceScope.Scoped => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped,
                    DiServiceScope.Transient => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient,
                    _ => throw new global::System.ArgumentOutOfRangeException(nameof(lifetime)),
                };
            }

            /// <summary>
            /// Applies registration tuples collected by Collect{Assembly}Services methods — possibly from
            /// projects with no reference to Microsoft.Extensions.DependencyInjection — to a real
            /// IServiceCollection. The tuple shape (Type, Type, int, string?, bool) uses only framework types
            /// so it is identical across every assembly, unlike a project-embedded class or enum would be.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCode("{{GeneratorInfo.Name}}", "{{GeneratorInfo.Version}}")]
            internal static class ServiceRegistrationExtensions
            {
                public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection MaterializeServices(
                    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
                    global::System.Collections.Generic.IEnumerable<(global::System.Type ServiceType, global::System.Type ImplementationType, int Lifetime, string? Key, bool IsHostedService)> registrations)
                {
                    foreach (var registration in registrations)
                    {
                        if (registration.IsHostedService)
                        {
                            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
                                services,
                                global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
                                    registration.ServiceType, registration.ImplementationType));
                            continue;
                        }

                        var lifetime = ((DiServiceScope)registration.Lifetime).ToServiceLifetime();
                        services.Add(registration.Key is null
                            ? new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                                registration.ServiceType, registration.ImplementationType, lifetime)
                            : new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                                registration.ServiceType, registration.Key, registration.ImplementationType, lifetime));
                    }

                    return services;
                }
            }
        }
        #endif
        """;
}
