//HintName: DIGenAttributes.g.cs
// <auto-generated by NkChinh.DI.Generator />
#if !DIGEN_EXCLUDE_ATTRIBUTES
#nullable enable
#pragma warning disable

namespace DIGen
{
    /// <summary>Registers the class as a singleton service using its concrete type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class SingletonServiceAttribute : global::System.Attribute
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public SingletonServiceAttribute() { }

        public SingletonServiceAttribute(string key) { Key = key; }
    }

    /// <summary>Registers the class as a singleton service exposed as <typeparamref name="TService"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class SingletonServiceAttribute<TService> : global::System.Attribute
        where TService : class
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public SingletonServiceAttribute() { }

        public SingletonServiceAttribute(string key) { Key = key; }
    }

    /// <summary>Registers the class as a scoped service using its concrete type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ScopedServiceAttribute : global::System.Attribute
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public ScopedServiceAttribute() { }

        public ScopedServiceAttribute(string key) { Key = key; }
    }

    /// <summary>Registers the class as a scoped service exposed as <typeparamref name="TService"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ScopedServiceAttribute<TService> : global::System.Attribute
        where TService : class
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public ScopedServiceAttribute() { }

        public ScopedServiceAttribute(string key) { Key = key; }
    }

    /// <summary>Registers the class as a transient service using its concrete type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class TransientServiceAttribute : global::System.Attribute
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public TransientServiceAttribute() { }

        public TransientServiceAttribute(string key) { Key = key; }
    }

    /// <summary>Registers the class as a transient service exposed as <typeparamref name="TService"/>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class TransientServiceAttribute<TService> : global::System.Attribute
        where TService : class
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public TransientServiceAttribute() { }

        public TransientServiceAttribute(string key) { Key = key; }
    }

    /// <summary>
    /// Marks an instance field or property for constructor injection. All [Inject] members of a
    /// partial class are grouped into a single generated constructor.
    /// When the project has no reference to Microsoft.Extensions.DependencyInjection,
    /// a keyed service warning (DIGEN012) is reported and the key is ignored.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Field | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class InjectAttribute : global::System.Attribute
    {
        /// <summary>Optional service key for keyed dependency injection.</summary>
        public string? Key { get; }

        public InjectAttribute() { }

        public InjectAttribute(string key) { Key = key; }
    }

    /// <summary>Lifetime values used by scope-locking attributes; independent of any DI package.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    internal enum DiServiceScope
    {
        Singleton = 0,
        Scoped = 1,
        Transient = 2,
    }

    /// <summary>
    /// Locks the lifetime any registration of this interface must use. Combine with
    /// <see cref="ServiceAttribute{TService}"/> to have the lifetime resolved automatically, or with
    /// an explicit lifetime attribute to have it checked for you.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class RequiredScopeAttribute : global::System.Attribute
    {
        public RequiredScopeAttribute(DiServiceScope lifetime)
        {
            Lifetime = lifetime;
        }

        public DiServiceScope Lifetime { get; }
    }

    /// <summary>
    /// Locks the lifetime a type this project doesn't own (a third-party interface, a <c>DbContext</c>, …)
    /// must use. Apply at assembly level in any project that directly references the type, so the
    /// type's own project never needs a dependency on it.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    internal sealed class RequiredExternalScopeAttribute : global::System.Attribute
    {
        public RequiredExternalScopeAttribute(global::System.Type interfaceType, DiServiceScope lifetime)
        {
            InterfaceType = interfaceType;
            Lifetime = lifetime;
        }

        public global::System.Type InterfaceType { get; }

        public DiServiceScope Lifetime { get; }
    }

    /// <summary>
    /// Registers the class as <typeparamref name="TService"/> using whatever lifetime
    /// <typeparamref name="TService"/> is locked to via <see cref="RequiredScopeAttribute"/> or
    /// <see cref="RequiredExternalScopeAttribute"/>.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ServiceAttribute<TService> : global::System.Attribute
        where TService : class
    {
        /// <summary>Optional service key; when set, the service is registered as a keyed service.</summary>
        public string? Key { get; }

        public ServiceAttribute() { }

        public ServiceAttribute(string key) { Key = key; }
    }

    /// <summary>
    /// Resolves [Inject] constructor parameters from an <see cref="global::System.IServiceProvider"/>
    /// using only BCL types — no dependency on Microsoft.Extensions.DependencyInjection.
    /// Generated constructors reference this helper via factory delegates when a class has
    /// both a generated [Inject] constructor and user-defined constructors.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    internal static class InjectServiceResolver
    {
        /// <summary>Resolves a required service; throws when missing.</summary>
        public static T GetRequired<T>(global::System.IServiceProvider sp)
        {
            var service = sp.GetService(typeof(T));
            if (service is null)
                throw new global::System.InvalidOperationException(
                    $"Cannot resolve service '{typeof(T)}' for constructor injection.");
            return (T)service;
        }

        /// <summary>Resolves an optional service, returning null when missing.</summary>
        public static T? GetOptional<T>(global::System.IServiceProvider sp) where T : class
        {
            return (T?)sp.GetService(typeof(T));
        }
    }
}

namespace DIGen.Generated
{
    /// <summary>
    /// Assembly-level marker describing this assembly's generated registration module.
    /// Referencing projects use it to generate an aggregator that chains all modules.
    /// Infrastructure attribute — do not apply manually.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    internal sealed class ServiceRegistrationModuleAttribute : global::System.Attribute
    {
        public ServiceRegistrationModuleAttribute(string methodName, string extensionsTypeName)
        {
            MethodName = methodName;
            ExtensionsTypeName = extensionsTypeName;
        }

        /// <summary>Name of the generated extension method, e.g. AddMyCompanyInfrastructureServices.</summary>
        public string MethodName { get; }

        /// <summary>Fully qualified name (without global::) of the static class declaring the method.</summary>
        public string ExtensionsTypeName { get; }
    }
}
#endif