//HintName: Demo.OrderService.DependencyInjection.g.cs
// <auto-generated by NkChinh.DI.Generator />
#nullable enable
#pragma warning disable

namespace Demo
{
    partial class OrderService
    {
        /// <summary>
        /// Constructor generated by NkChinh.DI.Generator from [Inject] members.
        /// </summary>
        public OrderService(global::Demo.IOrderRepository orderRepository, global::Demo.IPaymentGateway paymentGateway)
        {
            this._repository = orderRepository;
            this._gateway = paymentGateway;
        }
    }
}
