//HintName: ServiceCollectionExtensions.g.cs
// <auto-generated by NkChinh.DI.Generator />
#nullable enable
#pragma warning disable


namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Dependency-injection registrations generated for assembly 'SnapshotAssembly'
    /// from its own services and the services published by referenced projects.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    public static class SnapshotAssemblyServiceCollectionExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSnapshotAssemblyServices(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.AddScoped<global::Demo.IOrderRepository, global::Demo.OrderRepository>();
            services.AddTransient<global::Demo.ScratchBuffer>();
            services.AddKeyedSingleton<global::Demo.IPaymentGateway, global::Demo.StripeGateway>("stripe");
            return services;
        }
    }
}
