//HintName: DiServiceScopeExtensions.g.cs
// <auto-generated by NkChinh.DI.Generator />
#if !DIGEN_EXCLUDE_ATTRIBUTES
#nullable enable
#pragma warning disable

namespace DIGen
{
    /// <summary>Maps <see cref="DiServiceScope"/> to Microsoft.Extensions.DependencyInjection.ServiceLifetime.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    internal static class DiServiceScopeExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.ServiceLifetime ToServiceLifetime(
            this DiServiceScope lifetime) => lifetime switch
        {
            DiServiceScope.Singleton => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton,
            DiServiceScope.Scoped => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped,
            DiServiceScope.Transient => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(lifetime)),
        };
    }

    /// <summary>
    /// Applies registration tuples collected by Collect{Assembly}Services methods — possibly from
    /// projects with no reference to Microsoft.Extensions.DependencyInjection — to a real
    /// IServiceCollection. The tuple shape (Type, Type, int, string?, bool, Func{IServiceProvider, object}?)
    /// uses only framework types so it is identical across every assembly, unlike a project-embedded
    /// class or enum would be.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    internal static class ServiceRegistrationExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection MaterializeServices(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
            global::System.Collections.Generic.IEnumerable<(global::System.Type ServiceType, global::System.Type ImplementationType, int Lifetime, string? Key, bool IsHostedService, global::System.Func<global::System.IServiceProvider, object>? Factory)> registrations)
        {
            foreach (var registration in registrations)
            {
                if (registration.IsHostedService)
                {
                    global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(
                        services,
                        global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(
                            registration.ServiceType, registration.ImplementationType));
                    continue;
                }

                var lifetime = ((DiServiceScope)registration.Lifetime).ToServiceLifetime();

                if (registration.Factory is not null)
                {
                    services.Add(registration.Key is null
                        ? new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                            registration.ServiceType, registration.Factory, lifetime)
                        : new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                            registration.ServiceType, registration.Key,
                            (sp, key) => registration.Factory(sp), lifetime));
                }
                else
                {
                    services.Add(registration.Key is null
                        ? new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                            registration.ServiceType, registration.ImplementationType, lifetime)
                        : new global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor(
                            registration.ServiceType, registration.Key, registration.ImplementationType, lifetime));
                }
            }

            return services;
        }
    }
}
#endif