//HintName: ServiceDefinitions.g.cs
// <auto-generated by NkChinh.DI.Generator />
#nullable enable
#pragma warning disable


[assembly: global::DIGen.Generated.RegistrationModule("Snapshot.Assembly")]

[assembly: global::DIGen.Generated.ServiceDefinition(
    typeof(global::Demo.OrderRepository),
    typeof(global::Demo.IOrderRepository),
    (int)global::DIGen.DiServiceScope.Scoped,
    null,
    false,
    false,
    new string[] {  },
    new global::System.Type[] {  },
    new string[] {  },
    new bool[] {  })]

[assembly: global::DIGen.Generated.ServiceDefinition(
    typeof(global::Demo.ScratchBuffer),
    typeof(global::Demo.ScratchBuffer),
    (int)global::DIGen.DiServiceScope.Transient,
    null,
    false,
    false,
    new string[] {  },
    new global::System.Type[] {  },
    new string[] {  },
    new bool[] {  })]

[assembly: global::DIGen.Generated.ServiceDefinition(
    typeof(global::Demo.StripeGateway),
    typeof(global::Demo.IPaymentGateway),
    (int)global::DIGen.DiServiceScope.Singleton,
    "stripe",
    false,
    false,
    new string[] {  },
    new global::System.Type[] {  },
    new string[] {  },
    new bool[] {  })]
