//HintName: DiServiceScopeExtensions.g.cs
// <auto-generated by NkChinh.DI.Generator />
#if !DIGEN_EXCLUDE_ATTRIBUTES
#nullable enable
#pragma warning disable

namespace DIGen
{
    /// <summary>Maps <see cref="DiServiceScope"/> to Microsoft.Extensions.DependencyInjection.ServiceLifetime.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    internal static class DiServiceScopeExtensions
    {
        public static global::Microsoft.Extensions.DependencyInjection.ServiceLifetime ToServiceLifetime(
            this DiServiceScope lifetime) => lifetime switch
        {
            DiServiceScope.Singleton => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton,
            DiServiceScope.Scoped => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped,
            DiServiceScope.Transient => global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Transient,
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(lifetime)),
        };
    }
}
#endif