//HintName: ServiceCollectionExtensions.g.cs
// <auto-generated by NkChinh.DI.Generator />
#nullable enable
#pragma warning disable

[assembly: global::DIGen.Generated.ServiceRegistrationModuleAttribute("CollectSnapshotAssemblyServices", "Microsoft.Extensions.DependencyInjection.SnapshotAssemblyServiceCollectionExtensions")]

namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Dependency-injection registrations generated for assembly 'Snapshot.Assembly'.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("NkChinh.DI.Generator", "0.0.0")]
    public static class SnapshotAssemblyServiceCollectionExtensions
    {
        /// <summary>
        /// Collects all services declared with DIGen attributes in assembly 'Snapshot.Assembly' as plain
        /// data, requiring no reference to Microsoft.Extensions.DependencyInjection.
        /// </summary>
        public static void CollectSnapshotAssemblyServices(global::System.Collections.Generic.ICollection<(global::System.Type ServiceType, global::System.Type ImplementationType, int Lifetime, string? Key, bool IsHostedService)> registrations)
        {
            registrations.Add((typeof(global::Demo.IOrderRepository), typeof(global::Demo.OrderRepository), (int)global::DIGen.DiServiceScope.Scoped, null, false));
            registrations.Add((typeof(global::Demo.ScratchBuffer), typeof(global::Demo.ScratchBuffer), (int)global::DIGen.DiServiceScope.Transient, null, false));
            registrations.Add((typeof(global::Demo.IPaymentGateway), typeof(global::Demo.StripeGateway), (int)global::DIGen.DiServiceScope.Singleton, "stripe", false));
        }

        /// <summary>
        /// Registers all services declared with DIGen attributes in assembly 'Snapshot.Assembly'.
        /// </summary>
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSnapshotAssemblyServices(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            var registrations = new global::System.Collections.Generic.List<(global::System.Type ServiceType, global::System.Type ImplementationType, int Lifetime, string? Key, bool IsHostedService)>();
            CollectSnapshotAssemblyServices(registrations);
            return global::DIGen.ServiceRegistrationExtensions.MaterializeServices(services, registrations);
        }
    }
}
